### ISSUE TITLE
Undocumented dependency in example.py

### ISSUE THREAD

**Issue by aweinstein** [inuritdino/HiguchiFractalDimension#1]
The file ``example.py`` import the``tretsa``. However, this dependency is not documented, and I haven't been able to find a reference to this library.

**Comment by inuritdino** [comment]
Thanks for the interest, @aweinstein !

You are absolutely right. `tretsa` is not part of the project. The file `examples.py` is a technical leftover after the code's tests. The code in `examples.py` uses HFD and Detrended Fluctuation Analysis (DFA) to compare the results (dimension from HFD and alpha-exponent from DFA) for several known standard cases (White, Brown, Pink noise and RR intervals of the normal heart beat).  `test.png` shows the result of running the code. The DFA utility and noise-generators are part of our lab's complete dynamical toolbox TRETSA (not to be found at the moment).

To summarize:
One can **completely** discard the file `examples.py` and continue with the module itself `hfd.py`. You can generate the test-cases elsewhere or simply for White and Brown noise (as documented in README) + heart data:

```python
import numpy as np
import HiguchiFractalDimension as hfd

x = np.random.randn(10000)
y = np.empty(9900)
for i in range(x.size-100):
	y[i] = np.sum(x[:(i+100)])
	
## Note x is a Guassian noise, y is the original Brownian data used in Higuchi, Physica D, 1988.
hfd.hfd(x) # ~ 2.00
hfd.hfd(y) # ~ 1.50

## For the heart data in test.txt
z = np.loadtxt('test.txt')
z = z[z<180] ## clean non-realistic

hdf.hfd(z)

```

I will soon remove the file from the package. Sorry for the inconvenience.

P.S. If you are still interested in TRETSA I can talk to the maintainers of the package as I am not among the principal developers. The toolbox contains among other things:
DFA (all types)
DCCA (DFA on ND)
EMD/EEMD (empirical mode decomposition)
etc.

Thanks!

**Comment by aweinstein** [comment]
Thanks for the answer @inuritdino. 

Removing `example.py` will be enough.

By the way, thank you for sharing this code. It's much faster than a naive implementation!

**Comment by inuritdino** [comment]
Thanks!

You are welcome!

**Comment by inuritdino** [comment]
Dear @aweinstein ,

I thought that it is still good to have some exemplar code to run, so I kept `examples.py`, but removed `tretsa` dependency altogether. Another good thing is that this code gives you an idea on how *fast* different implementations (optimized vs. non-optimized) are for each test case.

Please, enjoy! And feel free to comment. 
I am closing the issue now...
