### ISSUE TITLE
Compilation problem

### ISSUE THREAD

**Issue by xumwang** [inuritdino/HiguchiFractalDimension#3]
$gcc -shared hfd.c -o libhfd.so -lm
/usr/bin/ld: /tmp/ccvhwJkf.o: relocation R_X86_64_PC32 against undefined symbol `trunc@@GLIBC_2.2.5' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status

**Comment by inuritdino** [comment]
Hi @xumwang !

Thanks for the interest! Have you tried the suggestion of the compiler?? Namely, to include `-fPIC` option?

It seems it is the issue (or the change in the default option list) of the gcc compiler and has been encountered recently in many other projects. I have discovered this issue too just today after seeing you comment. For me, `-fPIC` resolves the issue. Please, kindly do the same. The README installation instructions were updated accordingly: 

```
gcc -shared hfd.c -o libhfd.so -lm -fPIC
```

Thanks!

with best.
